name: fit_up
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  firebase_analytics: ^8.1.2
  cloud_firestore: ^2.2.2
  uuid: ^3.0.4
  path_provider: ^2.0.2
  firebase_storage: ^8.1.3
  progress_state_button: ^1.0.3
  google_sign_in: ^5.0.4
  fluttertoast: ^8.0.7
  slide_to_act: ^2.0.1
  smooth_page_indicator: ^1.0.0+2
  flutter_login_facebook: ^1.1.0
  flutter_signin_button: ^2.0.0
  url_launcher: ^6.0.10
  numberpicker: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    #- assets/images/logo2.jpeg
    #- assets/images/logo3.jpeg
    #- assets/images/new.jpg
    #- assets/images/salon.jpg
    #- assets/images/dumbell.jpg
    #- assets/images/dumbell2.jpg
    #- assets/images/gym3.jpeg
    #- assets/images/gym.jpg

